package didatrade.server;

/* these imported classes are generated by the contract */
import didatrade.DidaTradeMain;
import didatrade.DidaTradeMainServiceGrpc;

import io.grpc.stub.StreamObserver;

public class DidaTradeMainServiceImpl extends DidaTradeMainServiceGrpc.DidaTradeMainServiceImplBase {

    DidaTradeServerState server_state;
    
    public DidaTradeMainServiceImpl(DidaTradeServerState state) {
        this.server_state = state;
    }

    @Override
    public void populate(DidaTradeMain.PopulateRequest request, StreamObserver<DidaTradeMain.PopulateReply> responseObserver) {
	// for debug purposes
	System.out.println("Receiving populate request:" + request);

	int reqid    = request.getReqid();
	int quantity = request.getQuantity();

	// for debug purposes
	System.out.println("reqid " + reqid + " quantity " + quantity);

	DidaTradeCommand command = new DidaTradeCommand (DidaTradeAction.POPULATE, 0, quantity);

	// for debug purposes
	System.out.println("Adding populate request with reqid " + reqid + " to pending");

	RequestRecord request_record = new RequestRecord (reqid, command);
	this.server_state.req_history.addToPending (reqid, request_record);
	this.server_state.main_loop.wakeup ();
	boolean result = request_record.waitForResponse();

	// for debug purposes
	System.out.println("Result is ready for open request with reqid " + reqid);
	
	DidaTradeMain.PopulateReply response = DidaTradeMain.PopulateReply.newBuilder().setReqid(reqid).setResult(result).build();
	responseObserver.onNext(response);
	responseObserver.onCompleted();
    }

    @Override
    public void adduser(DidaTradeMain.AddUserRequest request, StreamObserver<DidaTradeMain.AddUserReply> responseObserver) {
	// for debug purposes
	System.out.println("Receiving add request:" + request);

	int reqid    = request.getReqid();
	int uid      = request.getUserid();
	int cash     = request.getCash();
	int stock    = request.getStock();

	// for debug purposes
	System.out.println("reqid " + reqid + " userid " + uid  + " cash " + cash + " stock " + stock);

	DidaTradeCommand command = new DidaTradeCommand (DidaTradeAction.ADDUSER, uid, cash, stock);

	// for debug purposes
	System.out.println("Adding add request with reqid " + reqid + " to pending");

	RequestRecord request_record = new RequestRecord (reqid, command);
	this.server_state.req_history.addToPending (reqid, request_record);
	this.server_state.main_loop.wakeup ();
	boolean result = request_record.waitForResponse();

	// for debug purposes
	System.out.println("Result is ready for add request with reqid " + reqid);
	
	DidaTradeMain.AddUserReply response =DidaTradeMain.AddUserReply.newBuilder().setReqid(reqid).setResult(result).build();
	
	responseObserver.onNext(response);
	responseObserver.onCompleted();
    }
    
    public void buy(DidaTradeMain.BuyRequest request, StreamObserver<DidaTradeMain.BuyReply> responseObserver) {
	// for debug purposes
	System.out.println("Receiving buy request:" + request);

	int reqid    = request.getReqid();
	int uid      = request.getUserid();
	int quantity = request.getQuantity();

	// for debug purposes
	System.out.println("reqid " + reqid + " userid " + uid  + " quantity " + quantity);

	DidaTradeCommand command = new DidaTradeCommand (DidaTradeAction.BUY, uid, quantity);

	// for debug purposes
	System.out.println("Adding buy request with reqid " + reqid + " to pending");

	RequestRecord request_record = new RequestRecord (reqid, command);
	this.server_state.req_history.addToPending (reqid, request_record);
	this.server_state.main_loop.wakeup ();
	boolean result = request_record.waitForResponse();

	// for debug purposes
	System.out.println("Result is ready for add request with reqid " + reqid);
	
	DidaTradeMain.BuyReply response =DidaTradeMain.BuyReply.newBuilder().setReqid(reqid).setResult(result).build();
	
	responseObserver.onNext(response);
	responseObserver.onCompleted();
    }

    @Override
    public void sell(DidaTradeMain.SellRequest request, StreamObserver<DidaTradeMain.SellReply> responseObserver) {
	// for debug purposes
	System.out.println("Receiving sell request:" + request);

	int reqid    = request.getReqid();
	int uid      = request.getUserid();
	int quantity = request.getQuantity();

	// for debug purposes
	System.out.println("reqid " + reqid + " userid " + uid  + " quantity " + quantity);

	DidaTradeCommand command = new DidaTradeCommand (DidaTradeAction.SELL, uid, quantity);

	// for debug purposes
	System.out.println("Adding sell request with reqid " + reqid + " to pending");

	RequestRecord request_record = new RequestRecord (reqid, command);
	this.server_state.req_history.addToPending (reqid, request_record);
	this.server_state.main_loop.wakeup ();
	boolean result = request_record.waitForResponse();

	// for debug purposes
	System.out.println("Result is ready for add request with reqid " + reqid);
	
	DidaTradeMain.SellReply response =DidaTradeMain.SellReply.newBuilder().setReqid(reqid).setResult(result).build();
	
	responseObserver.onNext(response);
	responseObserver.onCompleted();
    }

    @Override
    public void balance(DidaTradeMain.BalanceRequest request, StreamObserver<DidaTradeMain.BalanceReply> responseObserver) {
	// for debug purposes
	System.out.println("Receiving balance request:" + request);

	int reqid    = request.getReqid();
	int uid      = request.getUserid();

	// for debug purposes
	System.out.println("reqid " + reqid + " userid " + uid);

	DidaTradeCommand command = new DidaTradeCommand (DidaTradeAction.BALANCE, uid);

	// for debug purposes
	System.out.println("Adding balance request with reqid " + reqid + " to pending");

	RequestRecord request_record = new RequestRecord (reqid, command);
	this.server_state.req_history.addToPending (reqid, request_record);
	this.server_state.main_loop.wakeup ();
	boolean result = request_record.waitForResponse();

	// for debug purposes
	System.out.println("Result is ready for add request with reqid " + reqid);

	int balance = command.getQuantity();
	DidaTradeMain.BalanceReply response =DidaTradeMain.BalanceReply.newBuilder().setReqid(reqid).setResult(result).setBalance(balance).build();
	
	responseObserver.onNext(response);
	responseObserver.onCompleted();
    }

    @Override
    public void dump(DidaTradeMain.DumpRequest request, StreamObserver<DidaTradeMain.DumpReply> responseObserver) {
	// for debug purposes
	System.out.println("Receiving dump request:" + request);

	int reqid = request.getReqid();

	// for debug purposes
	System.out.println("reqid " + reqid);

	DidaTradeCommand command = new DidaTradeCommand (DidaTradeAction.DUMP);

	// for debug purposes
	System.out.println("Adding dump request with reqid " + reqid + " to pending");

	RequestRecord request_record = new RequestRecord (reqid, command);
	this.server_state.req_history.addToPending (reqid, request_record);
	this.server_state.main_loop.wakeup ();
	boolean result = request_record.waitForResponse();

	// for debug purposes
	System.out.println("Result is ready for dump request with reqid " + reqid);
	
	DidaTradeMain.DumpReply response =DidaTradeMain.DumpReply.newBuilder().setReqid(reqid).setResult(result).build();
	
	responseObserver.onNext(response);
	responseObserver.onCompleted();
    }
}
