package didatrade.server;

import java.util.List;

/* these imported classes are generated by the contract */
import didatrade.DidaTradeMain;
import didatrade.DidaTradeMainServiceGrpc;
import didatrade.DidaTradePaxos;
import didatrade.util.PhaseTwoResponseProcessor;
import io.grpc.stub.StreamObserver;

public class DidaTradeMainServiceImpl extends DidaTradeMainServiceGrpc.DidaTradeMainServiceImplBase {

	DidaTradeServerState server_state;

	public DidaTradeMainServiceImpl(DidaTradeServerState state) {
		this.server_state = state;
	}

	@Override
	public void populate(DidaTradeMain.PopulateRequest request,
			StreamObserver<DidaTradeMain.PopulateReply> responseObserver) {
		this.server_state.checkDebugState();

		int reqid = request.getReqid();
		int quantity = request.getQuantity();

		System.out.println("[CLIENT-RPC] populate reqid=" + reqid + " qty=" + quantity);

		DidaTradeCommand command = new DidaTradeCommand(DidaTradeAction.POPULATE, 0, quantity);
		RequestRecord request_record = new RequestRecord(reqid, command);

		this.decideRequestPath(reqid, request_record);

		boolean result = request_record.waitForResponse();

		System.out.println("[CLIENT-RPC] populate reqid=" + reqid + " -> result=" + result);

		DidaTradeMain.PopulateReply response = DidaTradeMain.PopulateReply.newBuilder().setReqid(reqid).setResult(result)
				.build();
		responseObserver.onNext(response);
		responseObserver.onCompleted();
	}

	@Override
	public void adduser(DidaTradeMain.AddUserRequest request,
			StreamObserver<DidaTradeMain.AddUserReply> responseObserver) {
		this.server_state.checkDebugState();

		int reqid = request.getReqid();
		int uid = request.getUserid();
		int cash = request.getCash();
		int stock = request.getStock();

		System.out.println("[CLIENT-RPC] adduser reqid=" + reqid + " uid=" + uid + " cash=" + cash + " stock=" + stock);

		DidaTradeCommand command = new DidaTradeCommand(DidaTradeAction.ADDUSER, uid, cash, stock);
		RequestRecord request_record = new RequestRecord(reqid, command);

		this.decideRequestPath(reqid, request_record);

		boolean result = request_record.waitForResponse();

		System.out.println("[CLIENT-RPC] adduser reqid=" + reqid + " -> result=" + result);

		DidaTradeMain.AddUserReply response = DidaTradeMain.AddUserReply.newBuilder().setReqid(reqid).setResult(result)
				.build();

		responseObserver.onNext(response);
		responseObserver.onCompleted();
	}

	public void buy(DidaTradeMain.BuyRequest request, StreamObserver<DidaTradeMain.BuyReply> responseObserver) {
		this.server_state.checkDebugState();

		int reqid = request.getReqid();
		int uid = request.getUserid();
		int quantity = request.getQuantity();

		System.out.println("[CLIENT-RPC] buy reqid=" + reqid + " uid=" + uid + " qty=" + quantity);

		DidaTradeCommand command = new DidaTradeCommand(DidaTradeAction.BUY, uid, quantity);
		RequestRecord request_record = new RequestRecord(reqid, command);

		this.decideRequestPath(reqid, request_record);

		boolean result = request_record.waitForResponse();

		System.out.println("[CLIENT-RPC] buy reqid=" + reqid + " -> result=" + result);

		DidaTradeMain.BuyReply response = DidaTradeMain.BuyReply.newBuilder().setReqid(reqid).setResult(result).build();

		responseObserver.onNext(response);
		responseObserver.onCompleted();
	}

	@Override
	public void sell(DidaTradeMain.SellRequest request, StreamObserver<DidaTradeMain.SellReply> responseObserver) {
		this.server_state.checkDebugState();

		int reqid = request.getReqid();
		int uid = request.getUserid();
		int quantity = request.getQuantity();

		System.out.println("[CLIENT-RPC] sell reqid=" + reqid + " uid=" + uid + " qty=" + quantity);

		DidaTradeCommand command = new DidaTradeCommand(DidaTradeAction.SELL, uid, quantity);
		RequestRecord request_record = new RequestRecord(reqid, command);

		this.decideRequestPath(reqid, request_record);

		boolean result = request_record.waitForResponse();

		System.out.println("[CLIENT-RPC] sell reqid=" + reqid + " -> result=" + result);

		DidaTradeMain.SellReply response = DidaTradeMain.SellReply.newBuilder().setReqid(reqid).setResult(result).build();

		responseObserver.onNext(response);
		responseObserver.onCompleted();
	}

	@Override
	public void balance(DidaTradeMain.BalanceRequest request,
			StreamObserver<DidaTradeMain.BalanceReply> responseObserver) {
		this.server_state.checkDebugState();

		int reqid = request.getReqid();
		int uid = request.getUserid();

		System.out.println("[CLIENT-RPC] balance reqid=" + reqid + " uid=" + uid);

		DidaTradeCommand command = new DidaTradeCommand(DidaTradeAction.BALANCE, uid);
		RequestRecord request_record = new RequestRecord(reqid, command);

		this.decideRequestPath(reqid, request_record);

		boolean result = request_record.waitForResponse();

		int balance = command.getQuantity();
		System.out.println("[CLIENT-RPC] balance reqid=" + reqid + " -> result=" + result + " balance=" + balance);

		DidaTradeMain.BalanceReply response = DidaTradeMain.BalanceReply.newBuilder().setReqid(reqid).setResult(result)
				.setBalance(balance).build();

		responseObserver.onNext(response);
		responseObserver.onCompleted();
	}

	@Override
	public void dump(DidaTradeMain.DumpRequest request, StreamObserver<DidaTradeMain.DumpReply> responseObserver) {
		this.server_state.checkDebugState();

		int reqid = request.getReqid();

		System.out.println("[CLIENT-RPC] dump reqid=" + reqid);

		DidaTradeCommand command = new DidaTradeCommand(DidaTradeAction.DUMP);
		RequestRecord request_record = new RequestRecord(reqid, command);

		this.decideRequestPath(reqid, request_record);

		boolean result = request_record.waitForResponse();

		System.out.println("[CLIENT-RPC] dump reqid=" + reqid + " -> result=" + result);

		DidaTradeMain.DumpReply response = DidaTradeMain.DumpReply.newBuilder().setReqid(reqid).setResult(result).build();

		responseObserver.onNext(response);
		responseObserver.onCompleted();
	}

	private void decideRequestPath(int reqid, RequestRecord request_record) {
		if (this.server_state.getFastPaxosMode()) {
			sendFastDirect(reqid, request_record);
		} else {
			this.server_state.req_history.addToPending(reqid, request_record);
			this.server_state.proposer.wakeup();
		}
	}

	private void sendFastDirect(int reqid, RequestRecord request_record) {
		int ballot = this.server_state.getCurrentBallot();
		int instance = this.server_state.getAndIncNextInstanceToPropose();

		// Still registered so the Executor can look it up by reqid and deliver
		// the client's response. Just never picked up by the Proposer's own loop.
		this.server_state.req_history.addToPending(reqid, request_record);

		request_record.setProposed(true);

		List<Integer> acceptors = this.server_state.scheduler.acceptors(ballot);
		int quorum = this.server_state.scheduler.quorum(ballot);
		int n_acceptors = acceptors.size();

		DidaTradePaxos.PhaseTwoRequest p2_request = DidaTradePaxos.PhaseTwoRequest.newBuilder()
				.setInstance(instance)
				.setRequestballot(ballot)
				.setValue(reqid)
				.build();

		System.out.println("[CLIENT-RPC] reqid=" + reqid + " going FAST direct to instance=" + instance);

		final PhaseTwoResponseProcessor tracker = new PhaseTwoResponseProcessor(quorum, n_acceptors);
		for (int target : acceptors) {
			this.server_state.async_stubs[target].phasetwo(p2_request,
					new io.grpc.stub.StreamObserver<DidaTradePaxos.PhaseTwoReply>() {
						public void onNext(DidaTradePaxos.PhaseTwoReply r) {
							tracker.onResponse(r.getAccepted());
							if (!r.getAccepted() && r.getMaxballot() > server_state.getCurrentBallot()) {
								server_state.setCurrentBallot(r.getMaxballot());
							}
							if (tracker.isImpossible()) {
								System.out.println("[CLIENT-RPC] reqid=" + reqid
										+ " fast direct failed at instance=" + instance
										+ ", falling back to classic Paxos via Proposer");
								request_record.setProposed(false);
								server_state.decInstanceIfUnused(instance);
								server_state.proposer.wakeup();
							}
						}

						public void onError(Throwable t) {
						}

						public void onCompleted() {
						}
					});
		}
	}
}
